[package]
name = "chess_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chess_rust"
path = "src/main.rs"

[lib]
name = "chess_rust"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.7"
